#page title
page_title                                : PlayTales                                # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 6444850972                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : PlayTales is the perfect companion for little audio play fans

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Peter Kurzok
your_link                                 : https://peterkurzok.de                     
your_city                                 : Gersfeld                    
email_address                             : playtales@peterkurzok.de
facebook_username                         :                                           
instagram_username                        : filmaniac
twitter_username                          : 
github_username                           : pkurzok
youtube_username                          :
mastodon_link                             : https://kind.social/@filmaniac



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Favorites
    description                           : Remember your favorite audio plays for quick access.
    fontawesome_icon_name                 : heart

  - title                                 : Apple Music Integration
    description                           : Access the largest streaming catalog and play ALL audio plays or music on offer from Apple.
    fontawesome_icon_name                 : music
    
  - title                                 : Voice output
    description                           : You can't read yet? No problem! Have the titles of artists and episodes read to you.
    fontawesome_icon_name                 : comment

  - title                                 : Easy to operate for kids
    description                           : Large control elements, selection of albums with Cover Flow or tile view.
    fontawesome_icon_name                 : child

  - title                                 : Save recently listened albums
    description                           : Pick up where you left off listening.
    fontawesome_icon_name                 : play-circle
  
  - title                                 : AirPlay and Bluetooth Support
    description                           : You have an external speaker? Great! PlayTales also plays directly to your ears or on the big speakers.
    fontawesome_icon_name                 : bullhorn

  - title                                 : Parents area
    description                           : Adapt PlayTales to the needs of your little ones. For example, by deactivating the search function. Only play what parents approve.
    fontawesome_icon_name                 : lock

  - title                                 : Dark and Lightmode
    description                           : Whether you listen during the day or in bed at night, PlayTales is dressed for the occasion.
    fontawesome_icon_name                 : lightbulb


# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.1

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#CA3943"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#ffffff"
feature_icons_background_color            : "#CA3943"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
